### ISSUE TITLE
rake db:migrate でエラー

### ISSUE THREAD

**Issue by youichiro** [NUTFes/group-manager#316]
`bundle exec rake db:migrate`

エラー
```
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /Users/you_pro/workspace/group-manager/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
ERROR:  relation "place_allow_lists" does not exist at character 323
STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
	                FROM pg_attribute a LEFT JOIN pg_attrdef d
	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	               WHERE a.attrelid = '"place_allow_lists"'::regclass
	                 AND a.attnum > 0 AND NOT a.attisdropped
	               ORDER BY a.attnum

rake aborted!
ActiveAdmin::DatabaseHitDuringLoad: Your file, app/models/place.rb (line 24), caused a database error while Active Admin was loading. This is most common when your database is missing or doesn't have the latest migrations applied. To prevent this error, move the code to a place where it will only be run when a page is rendered. One solution can be, to wrap the query in a Proc. Original error message: PG::UndefinedTable: ERROR:  relation "place_allow_lists" does not exist
LINE 5:                WHERE a.attrelid = '"place_allow_lists"'::reg...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"place_allow_lists"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
/Users/you_pro/workspace/group-manager/vendor/bundle/ruby/2.2.0/gems/activeadmin-1.1.0/lib/active_admin/error.rb:43:in `rescue in capture'
...
/Users/you_pro/.rbenv/versions/2.2.0/bin/bundle:23:in `load'
/Users/you_pro/.rbenv/versions/2.2.0/bin/bundle:23:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "place_allow_lists" does not exist
LINE 5:                WHERE a.attrelid = '"place_allow_lists"'::reg...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"place_allow_lists"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
/Users/you_pro/workspace/group-manager/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
...
/Users/you_pro/.rbenv/versions/2.2.0/bin/bundle:23:in `load'
/Users/you_pro/.rbenv/versions/2.2.0/bin/bundle:23:in `<main>'

Caused by:
PG::UndefinedTable: ERROR:  relation "place_allow_lists" does not exist
LINE 5:                WHERE a.attrelid = '"place_allow_lists"'::reg...
                                          ^
/Users/you_pro/workspace/group-manager/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
...
/Users/you_pro/.rbenv/versions/2.2.0/bin/bundle:23:in `load'
/Users/you_pro/.rbenv/versions/2.2.0/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

**Comment by youichiro** [comment]
打開案

**app/models/place.rb**

```diff
class Place < ActiveRecord::Base
  has_many :place_allow_lists

  # 団体カテゴリ毎に利用可能な場所を検索する
  scope :search_enable_place, ->(group_category_id){
    PlaceAllowList.where(group_category_id: group_category_id, enable: true).map {|allow_place|
      self.find(allow_place.place_id)
    }

  }

  def to_s # aciveAdmin, simple_formで表示名を指定する
      self.name_ja
  end

  # 選択肢の生成用，団体idで選択可能な場所を返す
  def self.collections(group_id)
    group_category_id = Group.find(group_id).group_category_id
    self.search_enable_place(group_category_id)
  end

  def self.usable_all_places
-    Place.joins(:place_allow_lists) \
-      .uniq.where(place_allow_lists:{enable:true}).order(:id)
+    # Place.joins(:place_allow_lists) \
+    #   .uniq.where(place_allow_lists:{enable:true}).order(:id)  # migrate時だけコメントアウト
  end
end
```

**app/models/fes_year.rb**

```diff
class FesYear < ActiveRecord::Base
  has_many :fes_date
  has_many :groups

  def self.this_year
-    FesYear.where(fes_year:Time.now.year).first
+    # FesYear.where(fes_year:Time.now.year).first  # migrate時だけコメントアウト
  end

  def to_s # aciveAdminで表示名を指定する
    self.fes_year
  end
end
```

**Comment by kkoike03** [comment]
fe4ece70da1f363d305bac52d4bf0905f793543c で解決
